### ISSUE TITLE
Sweep: DoG+Global+CE, intentionally trying to create grid cells

### ISSUE THREAD

**Issue by RylanSchaeffer** [RylanSchaeffer/FieteLab-No-Free-Lunch#8]
Experiment: Train networks on DoG place fields, trying to create grid cells under optimal conditions.

W&B Sweep: https://wandb.ai/rylan/mec-hpc-investigations/sweeps/r83jf81o?workspace=user-rylan

Sweep (N=8)

```
method: grid
metric:
  goal: minimize
  name: pos_decoding_err
parameters:
  Ng:
    values:
    - 4096
  Np:
    values:
    - 512
  activation:
    values:
    - relu
  batch_size:
    values:
    - 200
  bin_side_in_m:
    values:
    - 0.05
  box_height_in_m:
    values:
    - 2.2
  box_width_in_m:
    values:
    - 2.2
  initializer:
    values:
    - glorot_uniform
  is_periodic:
    values:
    - false
  learning_rate:
    values:
    - 0.0001
  n_epochs:
    values:
    - 20
  n_grad_steps_per_epoch:
    values:
    - 10000
  n_place_fields_per_cell:
    values:
    - 1
  n_recurrent_units_to_sample:
    values:
    - 256
  optimizer:
    values:
    - adam
    - rmsprop
  place_cell_rf:
    values:
    - 0.12
    - 0.2
  place_field_loss:
    values:
    - crossentropy
  place_field_normalization:
    values:
    - global
  place_field_values:
    values:
    - difference_of_gaussians
  readout_dropout:
    values:
    - 0
  rnn_type:
    values:
    - RNN
  seed:
    values:
    - 0
    - 1
  sequence_length:
    values:
    - 20
  surround_scale:
    values:
    - 2
  weight_decay:
    values:
    - 0.0001
program: mec_hpc_investigations/models/run_trainer_rylan.py
project: mec-hpc-investigations
```
